"""
Django settings for homeapp project.
 
Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""  
import os
from pathlib import Path
from decouple import config
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 

# Quick-start development settings - unsuitable for production  
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

if not DEBUG: 
    # إجبار المتصفح على استخدام HTTPS
    SECURE_SSL_REDIRECT = True
    
    # حماية ملفات تعريف الارتباط من السرقة عبر الجافاسكريبت
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    
    # حماية ضد الـ Clickjacking والـ XSS
    X_FRAME_OPTIONS = 'DENY'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # تفعيل HSTS (تأكد من أنك لن تعود لـ HTTP أبداً قبل تفعيلها)
    SECURE_HSTS_SECONDS = 31536000  # سنة كاملة
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
 
ALLOWED_HOSTS = ['amra-school.com','www.amra-school.com']
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
 
 
# Application definition 

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages', 
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',      # 👈 مهم
    'school_api',
    'amra',
    'Marconi',
    #'Andaloussia',
    #'Andaloussia2',
    'Presentation',
    'Mimosas_P',
    'Mimosas_M',
    #'La_Guirlande',
    #'Dream_School',
    #'Dream_School1',
    #'Paul_Arene',
    #'Initiative_2',
    'Benhanza',
    #'Benniss',
    'ZENITH',
    #'ZGHARI',
    'CHKAIL',
    'DiwaneAlmaarifa',
    'DiwaneAlmaarifa2',
    #'JEANCOCTEAU',
    'ALMADINA',
    'PALOALTO',
    'ALMADINA2',
    #'ZAIR_AL_AMIN',
    'LEADERSCHOOL',
    'CHAARANE',
    'MONECOLE',
    'SAMAE',
    #'MADINACALIFORNIE',
    #'NOUVELLEGENERATION',
    'ZGHARIKNT',
    #'AlAnware',
    'django_crontab',
    'axes',
    


]


# ✅ زيد هاد البلوك كامل باش Django يفهم التوكن
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # 👈 هادي هي الساروت!
        'rest_framework.authentication.SessionAuthentication',
    ],
    # اختياري: إلا بغيتي كلشي يكون مسدود بار ديفو (حنا ديجا درناها ف views)
    # 'DEFAULT_PERMISSION_CLASSES': [
    #    'rest_framework.permissions.IsAuthenticated',
    # ],
}

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend', # خاصها تكون هي الأولى
    'django.contrib.auth.backends.ModelBackend', # هادي ديال Django الأصلية
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # 👈 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'homeapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'homeapp.wsgi.application'
 

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

"""DATABASES = {
    'default': { 
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
    }
}
"""

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = "Africa/Casablanca"

USE_I18N = True 

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


# Default primary key field type 
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = "/static/"

STATICFILES_DIRS= [
    os.path.join(BASE_DIR, 'homeapp/static') 
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'image') 
MEDIA_URL = '/image/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' 

JSON_PATH = '../public_html/CHAARANE/db.json'
JSON_PATH_SAMAE = '../public_html/SAMAE/db.json'
JSON_PATH_MADINACALIFORNIE = '../public_html/MADINACALIFORNIE/db.json'
JSON_PATH_PRESENTATION = '../public_html/Presentation/db.json'
JSON_PATH_NOUVELLEGENERATION = '../public_html/NOUVELLEGENERATION/db.json'
JSON_PATH_ZGHARIKNT = '../public_html/ZGHARIKNT/db.json'
JSON_PATH_ZENITH = '../public_html/ZENITH/db.json' 
JSON_PATH_PAULARENE = '../public_html/PaulArene/db.json'
JSON_PATH_ALANWARE1 = '../public_html/ALANWARE/db1.json'
JSON_PATH_ALANWARE2 = '../public_html/ALANWARE/db2.json'
JSON_PATH_ALANWARE3 = '../public_html/ALANWARE/db3.json'


CRONJOBS = [
    # 00:00 كل يوم
    ('0 0 * * *', 'django.core.management.call_command', ['clear_scans']),
]


LOGIN_URL = '/api/login/'           # رابط صفحة الدخول
LOGIN_REDIRECT_URL = '/api/portal/' # فين يمشيو مورا الدخول
LOGOUT_REDIRECT_URL = '/api/login/' # فين يمشيو مورا الخروج


# إعدادات حماية django-axes

# شحال من محاولة خاطئة مسموح بيها قبل الحظر؟ (مثلاً 5 محاولات)
AXES_FAILURE_LIMIT = 5

# شحال ديال الوقت يبقى الـ IP محظور؟ (بالساعات). 1 تعني ساعة واحدة. 
# إلا بغيتي بالدقائق، تقدر تستخدم timedelta
from datetime import timedelta
AXES_COOLOFF_TIME = timedelta(minutes=30) # حظر لمدة 30 دقيقة

# واش الحظر يعتمد على الـ IP أو على اسم المستخدم (Username)؟
# من الأحسن تخليها تعتمد عليهم بجوج باش الهاكر مايبدلش غير الـ IP ويبقى يجرب
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

# تصفير العداد إلى المستخدم دخل كلمة المرور صحيحة قبل ما يفوت الحد
AXES_RESET_ON_SUCCESS = True

# (اختياري) واش بغيتي يبان للمستخدم خطأ 403 عادي، أو بغيتي توجهو لصفحة HTML مخصصة كتقوليه "راك تبلوكيتي"؟
AXES_LOCKOUT_TEMPLATE = 'lockout.html'


