# Generated by Django 4.2.26 on 2025-11-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='school',
            name='radius',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='api_key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
