# Generated by Django 4.2.26 on 2025-11-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0002_school_latitude_school_longitude_school_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='radius',
            field=models.IntegerField(default=100),
        ),
    ]
