# Generated by Django 4.2.26 on 2025-11-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0003_alter_school_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admin_badge_code',
            field=models.CharField(default='111111111111111111111111111111', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
