# Generated by Django 4.2.26 on 2025-11-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0004_school_admin_badge_code_alter_school_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='security_pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
