# Generated by Django 4.2.26 on 2025-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0005_school_security_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='security_pin',
            field=models.CharField(default='1111', max_length=4),
        ),
    ]
