# Generated by Django 4.2.26 on 2025-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0006_alter_school_security_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='active_admin_scan',
            field=models.BooleanField(default=False, verbose_name='Activer Scan Badge Admin'),
        ),
    ]
