# Generated by Django 4.2.26 on 2026-01-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0008_gardecategory_schoolclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='class_order',
            field=models.TextField(blank=True, default=''),
        ),
    ]
