# Generated by Django 4.2.26 on 2026-01-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0009_school_class_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='device_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='porte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
