# Generated by Django 4.2.26 on 2026-01-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0010_pickuprequest_device_id_pickuprequest_porte'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='school_api.school')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('school', 'key')},
            },
        ),
    ]
