# Generated by Django 4.2.26 on 2026-01-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0011_schoolport'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='porte_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
