# Generated by Django 4.2.26 on 2026-02-12 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_api', '0012_pickuprequest_porte_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'Retard')], default='PRESENT', max_length=10)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='school_api.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='school_api.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence Etudiant',
                'verbose_name_plural': 'Présences Etudiants',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
