# Generated by Django 4.2.26 on 2026-02-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0014_allstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpresence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='school_api.allstudents'),
        ),
    ]
