# Generated by Django 4.2.26 on 2026-02-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0015_alter_studentpresence_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_prof_account',
            field=models.BooleanField(default=False),
        ),
    ]
