# Generated by Django 4.2.26 on 2026-02-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0016_userprofile_is_prof_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpresence',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
