# Generated by Django 4.2.26 on 2026-02-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0017_alter_studentpresence_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequestBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pickup_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=150)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(max_length=150)),
                ('is_completed', models.BooleanField(default=False)),
                ('porte_label', models.CharField(blank=True, max_length=50, null=True)),
                ('porte', models.CharField(blank=True, max_length=20, null=True)),
                ('device_id', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at_original', models.DateTimeField()),
                ('backup_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
