# Generated by Django 4.2.26 on 2026-03-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0018_pickuprequestbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpresence',
            name='retard_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
